name: Testing

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm test
          npx update-badge
          git remote set-url origin https://git@github.com:HaroldMaster/test-actions.git
          git add .
          git commit -m "Badge updated"
          git push
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage